# Generated by Django 4.0.6 on 2022-07-15 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('draw_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('draw_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('winner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fk_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_draw.draw')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
